apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-jpaGenerator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.fullname" . }}-jpaGenerator
  template:
    metadata:
      labels:
        app: {{ include "myapp.fullname" . }}-jpaGenerator
    spec:
      containers:
          - name: jpaGenerator
            image: "{{ .Values.jpaGenerator.image.repository }}:{{ .Values.jpaGenerator.image.tag }}"
            imagePullPolicy: {{ .Values.jpaGenerator.image.pullPolicy }}
            ports:
              - containerPort: 8080