apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-spPromptConverter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.fullname" . }}-spPromptConverter
  template:
    metadata:
      labels:
        app: {{ include "myapp.fullname" . }}-spPromptConverter
    spec:
      containers:
          - name: spPromptConverter
            image: "{{ .Values.spPromptConverter.image.repository }}:{{ .Values.spPromptConverter.image.tag }}"
            imagePullPolicy: {{ .Values.spPromptConverter.image.pullPolicy }}
            ports:
              - containerPort: 8080