spring:
  ai:
    azure:
      openai:
        api-key: 86z7jRRHZRkxtVhoaXIWW1FTiRkuaxmxiCQ7gq8xSkmGEVHn00r1JQQJ99BKACHYHv6XJ3w3AAABACOGoN80
        endpoint: https://test-open-ai-dep.openai.azure.com/
        chat:
          options:
            deployment-name: gpt-4.1