name: Build and Deploy Modules to Azure App Service

on:
  push:
    branches:
      - main
      - spPromptGenerator

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Make gradlew executable (JpaGenerator)
        run: chmod +x gradlew
        working-directory: ./JpaGenerator

      - name: Build JpaGenerator (Gradle)
        run: ./gradlew clean build -x test
        working-directory: ./JpaGenerator

      - name: Make gradlew executable (SpPromptConverter)
        run: chmod +x gradlew
        working-directory: ./SpPromptConverter

      - name: Build SpPromptConverter (Gradle)
        run: ./gradlew clean build -x test
        working-directory: ./SpPromptConverter

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy JpaGenerator to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'spring-boot-generator'
          package: ${{ github.workspace }}/JpaGenerator/build/libs/*SNAPSHOT.jar

      - name: Deploy SpPromptConverter to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sp-prompt-generator'
          package: ${{ github.workspace }}/SpPromptConverter/build/libs/*SNAPSHOT.jar